# Generated by Django 5.2.13 on 2026-05-07 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_grade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='polls.question')),
            ],
        ),
    ]
