# Generated by Django 5.2.13 on 2026-05-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
