# Generated by Django 5.2.13 on 2026-05-07 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='difficulty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
