# Generated by Django 5.2.13 on 2026-05-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_difficulty_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='polls.choice'),
        ),
    ]
